apiVersion: v1
kind: Service
metadata:
  name: spiritual-tracker-service
spec:
  selector:
    app: spiritual-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
