apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiritual-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiritual-tracker
  template:
    metadata:
      labels:
        app: spiritual-tracker
    spec:
      containers:
      - name: spiritual-tracker-app
        image: spiritual-tracker-app:__IMAGE_TAG__
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/spiritual_health_tracker
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
          
