name: CI/CD Pipeline - Spring Boot App to Minikube

on:
  push:
    branches: [master]  # or your development branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set PowerShell Execution Policy
      #   run: |
      #     Set-ExecutionPolicy RemoteSigned -Scope Process -Force

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Generate unique image tag
        id: vars
        run: echo "IMAGE_TAG=build-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Spring Boot JAR
        run: |
          mvn clean package -DskipTests
          
      - name: Build Docker image
        run: |
          docker build -t spiritual-tracker-app:$IMAGE_TAG .

      - name: Load image into Minikube
        run: |
          minikube image load spiritual-tracker-app:$IMAGE_TAG

      - name: Replace image tag in deployment and apply
        run: |
          sed "s|image: spiritual-tracker-app.*|image: spiritual-tracker-app:$IMAGE_TAG |" spiritual-tracker-deployment.yaml | kubectl apply -f -
          kubectl apply -f spiritual-tracker-service.yaml

      - name: Apply PostgreSQL deployment and service
        run: |
          kubectl apply -f postgres-deployment.yaml
          kubectl apply -f postgres-service.yaml

      - name: Delete old pods
        run: |
          kubectl delete pod -l app=spiritual-tracker

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment spiritual-tracker-deployment
          
      - name: Wait for deployment to complete
        run: |
          kubectl rollout status deployment spiritual-tracker-deployment